---
- name: install hhvm gpg key
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present

- name: add hhvm deb repository
  apt_repository: repo='deb http://dl.hhvm.com/debian wheezy main' state=present

- name: install hhvm packages
  apt:
    name: {{ packages }}
    state: latest
    update_cache: yes
    force: yes
  vars:
    packages:
      - hhvm-fastcgi
  notify: restart hhvm

- name: check hhvm path
  shell: which hhvm
  register: current_hhvm
  ignore_errors: True

- name: symlink hhvm as php
  file: src="{{ current_hhvm.stdout }}" dest=/usr/bin/php state=link
